#!/usr/bin/env python3

import sys
import os
import inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
sys.path.insert(0, current_dir)

from src.data_mesh_cli.DataMeshCli import DataMeshCli

client = DataMeshCli(caller_name='data-mesh-cli')
client.run()